name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify hybrid_parser
        run: |
          cd smallAI/src
          python hybrid_parser.py "show failed logins"

      - name: Lint (optional)
        run: |
          if command -v ruff >/dev/null 2>&1; then ruff check smallAI || true; fi

      # Optional: build Docker image
      # - name: Build Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: smallAI/
      #     push: false
      #     tags: smallai:ci
